---
kind: pipeline
type: docker
name: default

steps:
- name: build-server
  image: golang:1.13
  commands:
  - make build
  when:
    event: push

- name: publish-server-image
  image: plugins/gcr
  settings:
    registry: gcr.io
    repo: wheresthetrain-nyc/wtt
    tag: "${DRONE_COMMIT}"
    json_key:
      from_secret: google_credentials
    when:
      branch: [master]
      event: push

- name: deploy
  image: nytimes/drone-gae
  settings:
    action: deploy
    project: wheresthetrain-nyc
    dir: cmd/server
    app_file: app.yaml
    addl_args: '{ "--image-url": "gcr.io/wheresthetrain-nyc/wtt:${DRONE_COMMIT}" }'
    version: "${DRONE_COMMIT}"
    vars: '{ "KEY": "$$MTA_KEY" }'
  secrets:
    - source: google_credentials
      target: GAE_CREDENTIALS
    - source: mta_key
      target: MTA_KEY
  when:
    branch: [master]
    event: push
