runtime: go
api_version: go1.8
module: default

inbound_services:
- warmup

handlers:
- url : /
  static_files: pages/index.html
  upload: pages/index.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /data
  static_dir: data
  http_headers:
    Content-Type: application/json

- url: /images
  static_dir: images

- url: /svc/.*
  script: _go_app

- url: /.well-known/.*
  script: _go_app

- url: /_ah/warmup
  script: _go_app
  login: admin

- url : /
  static_dir: pages

env_variables:
  MTA_KEY: XXX
